create table if not exists shows (
	id_show uuid default uuid_generate_v1mc() primary key not null,
	title varchar(255) not null,
	native_title varchar(255),
	romanization varchar(255),
	release_date timestamp(6) with time zone,
	completed_date timestamp(6) with time zone,
	country varchar(255), 
	genre varchar(255) not null, 
	company varchar(255), 
	main_character uuid,
	side_character1 uuid,
	side_character2 uuid,
	show_image varchar(255),
	main_character_actor uuid,
	side_character_actor1 uuid,
	side_character_actor2 uuid,
	main_character_image varchar(255),
	side_character_image1 varchar(255),
	side_character_image2 varchar(255),
	seasons integer,
	episodes integer,
	synopsis text not null,
	comments uuid[],
	added_at timestamp(6) with time zone default Now() not null,
	updated_at timestamp(6) with time zone
);