import { createStore } from 'vuex';
import DataService from '../../service/dataService';
export default createStore({
  state: {
    token: '',
    user: null,
    role: '',
    years: [
      1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
      2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025,
    ],
    listStatus: ['watching', 'completed', 'paused', 'dropped', 'planned'],
    airingStatus: ['Airing', 'Finished', 'Not released', 'Not airing'],
    genres: [
      'Drama',
      'Sci-Fi',
      'Fantasy',
      'Action',
      'Adventure',
      'Mystery',
      'Thriller',
      'Horror',
      'Comedy',
      'Crime',
      'Romance',
      'Family',
      'History',
      'War',
      'Animation',
      'Music',
    ],
    countries: [
      'Afghanistan',
      'Albania',
      'Algeria',
      'Andorra',
      'Angola',
      'Antigua and Barbuda',
      'Argentina',
      'Armenia',
      'Australia',
      'Austria',
      'Azerbaijan',
      'The Bahamas',
      'Bahrain',
      'Bangladesh',
      'Barbados',
      'Belarus',
      'Belgium',
      'Belize',
      'Benin',
      'Bhutan',
      'Bolivia',
      'Bosnia and Herzegovina',
      'Botswana',
      'Brazil',
      'Brunei',
      'Bulgaria',
      'Burkina Faso',
      'Burundi',
      'Cambodia',
      'Cameroon',
      'Canada',
      'Cape Verde',
      'Central African Republic',
      'Chad',
      'Chile',
      'China',
      'Colombia',
      'Comoros',
      'Congo, Republic of the',
      'Congo, Democratic Republic of the',
      'Costa Rica',
      `Cote d'Ivoire`,
      'Croatia',
      'Cuba',
      'Cyprus',
      'Czech Republic',
      'Denmark',
      'Djibouti',
      'Dominica',
      'Dominican Republic',
      'East Timor (Timor-Leste)',
      'Ecuador',
      'Egypt',
      'El Salvador',
      'Equatorial Guinea',
      'Eritrea',
      'Estonia',
      'Ethiopia',
      'Fiji',
      'Finland',
      'France',
      'Gabon',
      'The Gambia',
      'Georgia',
      'Germany',
      'Ghana',
      'Greece',
      'Grenada',
      'Guatemala',
      'Guinea',
      'Guinea-Bissau',
      'Guyana',
      'Haiti',
      'Honduras',
      'Hungary',
      'Iceland',
      'India',
      'Indonesia',
      'Iran',
      'Iraq',
      'Ireland',
      'Israel',
      'Italy',
      'Jamaica',
      'Japan',
      'Jordan',
      'Kazakhstan',
      'Kenya',
      'Kiribati',
      'Korea, North',
      'Korea, South',
      'Kosovo',
      'Kuwait',
      'Kyrgyzstan',
      'Laos',
      'Latvia',
      'Lebanon',
      'Lesotho',
      'Liberia',
      'Libya',
      'Liechtenstein',
      'Lithuania',
      'Luxembourg',
      'Macedonia',
      'Madagascar',
      'Malawi',
      'Malaysia',
      'Maldives',
      'Mali',
      'Malta',
      'Marshall Islands',
      'Mauritania',
      'Mauritius',
      'Mexico',
      'Micronesia, Federated States of',
      'Moldova',
      'Monaco',
      'Mongolia',
      'Montenegro',
      'Morocco',
      'Mozambique',
      'Myanmar (Burma)',
      'Namibia',
      'Nauru',
      'Nepal',
      'Netherlands',
      'New Zealand',
      'Nicaragua',
      'Niger',
      'Nigeria',
      'Norway',
      'Oman',
      'Pakistan',
      'Palau',
      'Panama',
      'Papua New Guinea',
      'Paraguay',
      'Peru',
      'Philippines',
      'Poland',
      'Portugal',
      'Qatar',
      'Romania',
      'Russia',
      'Rwanda',
      'Saint Kitts and Nevis',
      'Saint Lucia',
      'Saint Vincent and the Grenadines',
      'Samoa',
      'San Marino',
      'Sao Tome and Principe',
      'Saudi Arabia',
      'Senegal',
      'Serbia',
      'Seychelles',
      'Sierra Leone',
      'Singapore',
      'Slovakia',
      'Slovenia',
      'Solomon Islands',
      'Somalia',
      'South Africa',
      'South Sudan',
      'Spain',
      'Sri Lanka',
      'Sudan',
      'Suriname',
      'Swaziland',
      'Sweden',
      'Switzerland',
      'Syria',
      'Taiwan',
      'Tajikistan',
      'Tanzania',
      'Thailand',
      'Togo',
      'Tonga',
      'Trinidad and Tobago',
      'Tunisia',
      'Turkey',
      'Turkmenistan',
      'Tuvalu',
      'Uganda',
      'Ukraine',
      'United Arab Emirates',
      'United Kingdom',
      'United States of America',
      'Uruguay',
      'Uzbekistan',
      'Vanuatu',
      'Vatican City (Holy See)',
      'Venezuela',
      'Vietnam',
      'Yemen',
      'Zambia',
      'Zimbabwe',
    ],
    timezones: [
      'Asia/Kabul',
      'Europe/Tirane',
      'Africa/Algiers',
      'Pacific/Pago_Pago',
      'Europe/Andorra',
      'Africa/Luanda',
      'America/Anguilla',
      'Antarctica/Casey',
      'Antarctica/Davis',
      'Antarctica/DumontDUrville',
      'Antarctica/Mawson',
      'Antarctica/McMurdo',
      'Antarctica/Palmer',
      'Antarctica/Rothera',
      'Antarctica/Syowa',
      'Antarctica/Troll',
      'Antarctica/Vostok',
      'America/Antigua',
      'America/Argentina/Buenos_Aires',
      'America/Argentina/Catamarca',
      'America/Argentina/Cordoba',
      'America/Argentina/Jujuy',
      'America/Argentina/La_Rioja',
      'America/Argentina/Mendoza',
      'America/Argentina/Rio_Gallegos',
      'America/Argentina/Salta',
      'America/Argentina/San_Juan',
      'America/Argentina/San_Luis',
      'America/Argentina/Tucuman',
      'America/Argentina/Ushuaia',
      'Asia/Yerevan',
      'America/Aruba',
      'Antarctica/Macquarie',
      'Australia/Adelaide',
      'Australia/Brisbane',
      'Australia/Broken_Hill',
      'Australia/Darwin',
      'Australia/Eucla',
      'Australia/Hobart',
      'Australia/Lindeman',
      'Australia/Lord_Howe',
      'Australia/Melbourne',
      'Australia/Perth',
      'Australia/Sydney',
      'Europe/Vienna',
      'Asia/Baku',
      'America/Nassau',
      'Asia/Bahrain',
      'Asia/Dhaka',
      'America/Barbados',
      'Europe/Minsk',
      'Europe/Brussels',
      'America/Belize',
      'Africa/Porto-Novo',
      'Atlantic/Bermuda',
      'Asia/Thimphu',
      'America/La_Paz',
      'America/Kralendijk',
      'Europe/Sarajevo',
      'Africa/Gaborone',
      'America/Araguaina',
      'America/Bahia',
      'America/Belem',
      'America/Boa_Vista',
      'America/Campo_Grande',
      'America/Cuiaba',
      'America/Eirunepe',
      'America/Fortaleza',
      'America/Maceio',
      'America/Manaus',
      'America/Noronha',
      'America/Porto_Velho',
      'America/Recife',
      'America/Rio_Branco',
      'America/Santarem',
      'America/Sao_Paulo',
      'Indian/Chagos',
      'Asia/Brunei',
      'Europe/Sofia',
      'Africa/Ouagadougou',
      'Africa/Bujumbura',
      'Asia/Phnom_Penh',
      'Africa/Douala',
      'America/Atikokan',
      'America/Blanc-Sablon',
      'America/Cambridge_Bay',
      'America/Creston',
      'America/Dawson',
      'America/Dawson_Creek',
      'America/Edmonton',
      'America/Fort_Nelson',
      'America/Glace_Bay',
      'America/Goose_Bay',
      'America/Halifax',
      'America/Inuvik',
      'America/Iqaluit',
      'America/Moncton',
      'America/Nipigon',
      'America/Pangnirtung',
      'America/Rainy_River',
      'America/Rankin_Inlet',
      'America/Regina',
      'America/Resolute',
      'America/St_Johns',
      'America/Swift_Current',
      'America/Thunder_Bay',
      'America/Toronto',
      'America/Vancouver',
      'America/Whitehorse',
      'America/Winnipeg',
      'America/Yellowknife',
      'Atlantic/Cape_Verde',
      'America/Cayman',
      'Africa/Bangui',
      'Africa/Ndjamena',
      'America/Punta_Arenas',
      'America/Santiago',
      'Pacific/Easter',
      'Asia/Shanghai',
      'Asia/Urumqi',
      'Indian/Christmas',
      'Indian/Cocos',
      'America/Bogota',
      'Indian/Comoro',
      'Africa/Brazzaville',
      'Africa/Kinshasa',
      'Africa/Lubumbashi',
      'Pacific/Rarotonga',
      'America/Costa_Rica',
      'Europe/Zagreb',
      'America/Havana',
      'America/Curacao',
      'Asia/Famagusta',
      'Asia/Nicosia',
      'Europe/Prague',
      'Africa/Abidjan',
      'Europe/Copenhagen',
      'Africa/Djibouti',
      'America/Dominica',
      'America/Santo_Domingo',
      'America/Guayaquil',
      'Pacific/Galapagos',
      'Africa/Cairo',
      'America/El_Salvador',
      'Africa/Malabo',
      'Africa/Asmara',
      'Europe/Tallinn',
      'Africa/Addis_Ababa',
      'Atlantic/Stanley',
      'Atlantic/Faroe',
      'Pacific/Fiji',
      'Europe/Helsinki',
      'Europe/Paris',
      'America/Cayenne',
      'Pacific/Gambier',
      'Pacific/Marquesas',
      'Pacific/Tahiti',
      'Indian/Kerguelen',
      'Africa/Libreville',
      'Africa/Banjul',
      'Asia/Tbilisi',
      'Europe/Berlin',
      'Europe/Busingen',
      'Africa/Accra',
      'Europe/Gibraltar',
      'Europe/Athens',
      'America/Danmarkshavn',
      'America/Nuuk',
      'America/Scoresbysund',
      'America/Thule',
      'America/Grenada',
      'America/Guadeloupe',
      'Pacific/Guam',
      'America/Guatemala',
      'Europe/Guernsey',
      'Africa/Conakry',
      'Africa/Bissau',
      'America/Guyana',
      'America/Port-au-Prince',
      'Europe/Vatican',
      'America/Tegucigalpa',
      'Asia/Hong_Kong',
      'Europe/Budapest',
      'Atlantic/Reykjavik',
      'Asia/Kolkata',
      'Asia/Jakarta',
      'Asia/Jayapura',
      'Asia/Makassar',
      'Asia/Pontianak',
      'Asia/Tehran',
      'Asia/Baghdad',
      'Europe/Dublin',
      'Europe/Isle_of_Man',
      'Asia/Jerusalem',
      'Europe/Rome',
      'America/Jamaica',
      'Asia/Tokyo',
      'Europe/Jersey',
      'Asia/Amman',
      'Asia/Almaty',
      'Asia/Aqtau',
      'Asia/Aqtobe',
      'Asia/Atyrau',
      'Asia/Oral',
      'Asia/Qostanay',
      'Asia/Qyzylorda',
      'Africa/Nairobi',
      'Pacific/Kanton',
      'Pacific/Kiritimati',
      'Pacific/Tarawa',
      'Asia/Pyongyang',
      'Asia/Seoul',
      'Asia/Kuwait',
      'Asia/Bishkek',
      'Asia/Vientiane',
      'Europe/Riga',
      'Asia/Beirut',
      'Africa/Maseru',
      'Africa/Monrovia',
      'Africa/Tripoli',
      'Europe/Vaduz',
      'Europe/Vilnius',
      'Europe/Luxembourg',
      'Asia/Macau',
      'Europe/Skopje',
      'Indian/Antananarivo',
      'Africa/Blantyre',
      'Asia/Kuala_Lumpur',
      'Asia/Kuching',
      'Indian/Maldives',
      'Africa/Bamako',
      'Europe/Malta',
      'Pacific/Kwajalein',
      'Pacific/Majuro',
      'America/Martinique',
      'Africa/Nouakchott',
      'Indian/Mauritius',
      'Indian/Mayotte',
      'America/Bahia_Banderas',
      'America/Cancun',
      'America/Chihuahua',
      'America/Hermosillo',
      'America/Matamoros',
      'America/Mazatlan',
      'America/Merida',
      'America/Mexico_City',
      'America/Monterrey',
      'America/Ojinaga',
      'America/Tijuana',
      'Pacific/Chuuk',
      'Pacific/Kosrae',
      'Pacific/Pohnpei',
      'Europe/Chisinau',
      'Europe/Monaco',
      'Asia/Choibalsan',
      'Asia/Hovd',
      'Asia/Ulaanbaatar',
      'Europe/Podgorica',
      'America/Montserrat',
      'Africa/Casablanca',
      'Africa/Maputo',
      'Asia/Yangon',
      'Africa/Windhoek',
      'Pacific/Nauru',
      'Asia/Kathmandu',
      'Europe/Amsterdam',
      'Pacific/Noumea',
      'Pacific/Auckland',
      'Pacific/Chatham',
      'America/Managua',
      'Africa/Niamey',
      'Africa/Lagos',
      'Pacific/Niue',
      'Pacific/Norfolk',
      'Pacific/Saipan',
      'Europe/Oslo',
      'Asia/Muscat',
      'Asia/Karachi',
      'Pacific/Palau',
      'Asia/Gaza',
      'Asia/Hebron',
      'America/Panama',
      'Pacific/Bougainville',
      'Pacific/Port_Moresby',
      'America/Asuncion',
      'America/Lima',
      'Asia/Manila',
      'Pacific/Pitcairn',
      'Europe/Warsaw',
      'Atlantic/Azores',
      'Atlantic/Madeira',
      'Europe/Lisbon',
      'America/Puerto_Rico',
      'Asia/Qatar',
      'Europe/Bucharest',
      'Asia/Anadyr',
      'Asia/Barnaul',
      'Asia/Chita',
      'Asia/Irkutsk',
      'Asia/Kamchatka',
      'Asia/Khandyga',
      'Asia/Krasnoyarsk',
      'Asia/Magadan',
      'Asia/Novokuznetsk',
      'Asia/Novosibirsk',
      'Asia/Omsk',
      'Asia/Sakhalin',
      'Asia/Srednekolymsk',
      'Asia/Tomsk',
      'Asia/Ust-Nera',
      'Asia/Vladivostok',
      'Asia/Yakutsk',
      'Asia/Yekaterinburg',
      'Europe/Astrakhan',
      'Europe/Kaliningrad',
      'Europe/Kirov',
      'Europe/Moscow',
      'Europe/Samara',
      'Europe/Saratov',
      'Europe/Ulyanovsk',
      'Europe/Volgograd',
      'Africa/Kigali',
      'Indian/Reunion',
      'America/St_Barthelemy',
      'Atlantic/St_Helena',
      'America/St_Kitts',
      'America/St_Lucia',
      'America/Marigot',
      'America/Miquelon',
      'America/St_Vincent',
      'Pacific/Apia',
      'Europe/San_Marino',
      'Africa/Sao_Tome',
      'Asia/Riyadh',
      'Africa/Dakar',
      'Europe/Belgrade',
      'Indian/Mahe',
      'Africa/Freetown',
      'Asia/Singapore',
      'America/Lower_Princes',
      'Europe/Bratislava',
      'Europe/Ljubljana',
      'Pacific/Guadalcanal',
      'Africa/Mogadishu',
      'Africa/Johannesburg',
      'Atlantic/South_Georgia',
      'Africa/Juba',
      'Africa/Ceuta',
      'Atlantic/Canary',
      'Europe/Madrid',
      'Asia/Colombo',
      'Africa/Khartoum',
      'America/Paramaribo',
      'Arctic/Longyearbyen',
      'Africa/Mbabane',
      'Europe/Stockholm',
      'Europe/Zurich',
      'Asia/Damascus',
      'Asia/Taipei',
      'Asia/Dushanbe',
      'Africa/Dar_es_Salaam',
      'Asia/Bangkok',
      'Asia/Dili',
      'Africa/Lome',
      'Pacific/Fakaofo',
      'Pacific/Tongatapu',
      'America/Port_of_Spain',
      'Africa/Tunis',
      'Europe/Istanbul',
      'Asia/Ashgabat',
      'America/Grand_Turk',
      'Pacific/Funafuti',
      'Africa/Kampala',
      'Europe/Kiev',
      'Europe/Simferopol',
      'Europe/Uzhgorod',
      'Europe/Zaporozhye',
      'Asia/Dubai',
      'Europe/London',
      'America/Adak',
      'America/Anchorage',
      'America/Boise',
      'America/Chicago',
      'America/Denver',
      'America/Detroit',
      'America/Indiana/Indianapolis',
      'America/Indiana/Knox',
      'America/Indiana/Marengo',
      'America/Indiana/Petersburg',
      'America/Indiana/Tell_City',
      'America/Indiana/Vevay',
      'America/Indiana/Vincennes',
      'America/Indiana/Winamac',
      'America/Juneau',
      'America/Kentucky/Louisville',
      'America/Kentucky/Monticello',
      'America/Los_Angeles',
      'America/Menominee',
      'America/Metlakatla',
      'America/New_York',
      'America/Nome',
      'America/North_Dakota/Beulah',
      'America/North_Dakota/Center',
      'America/North_Dakota/New_Salem',
      'America/Phoenix',
      'America/Sitka',
      'America/Yakutat',
      'Pacific/Honolulu',
      'Pacific/Midway',
      'Pacific/Wake',
      'America/Montevideo',
      'Asia/Samarkand',
      'Asia/Tashkent',
      'Pacific/Efate',
      'America/Caracas',
      'Asia/Ho_Chi_Minh',
      'America/Tortola',
      'America/St_Thomas',
      'Pacific/Wallis',
      'Africa/El_Aaiun',
      'Asia/Aden',
      'Africa/Lusaka',
      'Africa/Harare',
      'Europe/Marieha',
    ],
  },
  mutations: {
    setToken(state, token) {
      state.token = token;
    },
    setUser(state, user) {
      state.user = user;
    },
    setRole(state, role) {
      state.role = role;
    },
  },
  actions: {
    async login({ commit }, token) {
      commit('setToken', token);
      if (token !== '') {
        console.log('REACHED');
        const base64Url = token.split('.')[1];
        const base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
        const user = JSON.parse(window.atob(base64));
        localStorage.setItem('userId', user.id_user);
        localStorage.setItem('userRoleId', user.role_id);
        localStorage.setItem('profileImage', user.profile_image);
        localStorage.setItem('username', user.username);
        // console.log('USER FROM STORE: ', user);

        const isAdmin = await DataService.isAdmin(user);
        if (isAdmin) {
          console.log('IS ADMIN LOGIN');
          commit('setRole', 'Admin');
        } else {
          commit('setRole', 'User');
        }
        commit('setUser', user);
      } else {
        commit('setUser', null);
      }
    },
  },
  getters: {
    getUser(state) {
      return state.user;
    },
    getRole(state) {
      return state.role;
    },
    getCountries(state) {
      return state.countries;
    },
    getGenres(state) {
      return state.genres;
    },
    getYears(state) {
      return state.years;
    },
    getAiringStatus(state) {
      return state.airingStatus;
    },
    getListStatus(state) {
      return state.listStatus;
    },
    getTimezone(state) {
      return state.timezones;
    },
  },
  modules: {},
});
